name: auto_connect
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

scripts:
  mobx: "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  build:
    android: "fvm flutter build apk --split-per-abi"
    ios: "fvm flutter build ios"
    web: "fvm flutter build web --release"
  get: "fvm flutter pub get"
  clean: "fvm flutter clean"
  run: "fvm flutter run"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.18.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  dio: ^5.3.0
  connectivity_plus: ^3.0.2
  local_auth: ^2.1.6
  flutter_svg: ^2.0.5
  encrypt: ^5.0.1
  loading_animation_widget: ^1.2.0+4
  permission_handler: ^10.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.2.3
  auto_size_text: ^3.0.0
  path: ^1.8.2
  get_it: ^7.2.0
  url_launcher: ^6.1.8
  go_router: ^6.0.3
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  image: ^4.1.3
  file: ^6.1.2
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  mobx_codegen: ^2.0.7+3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSan
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
